theme: jekyll-theme-cayman
lsi: false
safe: true
baseurl: /stackoverflow_survey_analysis
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: roug
plugins:
  - jekyll-relative-links
